### PR TITLE
Handling user defined hook script with multiple handles

### PR DESCRIPTION
**Pull request by asmcc**
In original examples from dehydrated (see dehydrated/docs/examples/hook.sh) you can find an universal hook script using multiple handles. Your "exit_hook" can not work with this original example of dehydrated, since it can not parce the parameters.
Furthermore in last versions you created a separate section and second user value for separate "deploy hook script". I find this idea not good and such a way wrong.
My changes revert partially this separation for "deploy hook script" and introduce an universal handling for all exit hooks accordingly original example of dehydrated. Now, exit_hook is executed ALWAYS at end of pdns_api.sh. Separation between individual hooks occurs inside of user defined exit hook script. This script handles not only "exit_hook", but also other hooks, for example "deploy_cert".

### CODE REVIEW

**Comment by silkeh** [comment]
First off, thanks for taking the time to submit a PR. However, I'm afraid I can't accept it.

> In original examples from dehydrated (see dehydrated/docs/examples/hook.sh) you can find an universal hook script using multiple handles. Your "exit_hook" can not work with this original example of dehydrated, since it can not parce the parameters.

It is not meant to. `PDNS_EXIT_HOOK` and `PDNS_DEPLOY_CERT_HOOK` offer an easy way to hook a simple script to this one. For a fully compatible hook, I would recommend anyone create a custom hook (based on the example) and incorporate `pdns_api.sh` in it.

> Furthermore in last versions you created a separate section and second user value for separate "deploy hook script". I find this idea not good and such a way wrong.

Both hooks were contributed because there is a use case for it. The hooks are not meant to be fully featured, only to do simple things (like an Nginx reload).

> My changes revert partially this separation for "deploy hook script" and introduce an universal handling for all exit hooks accordingly original example of dehydrated. Now, exit_hook is executed ALWAYS at end of pdns_api.sh. Separation between individual hooks occurs inside of user defined exit hook script. This script handles not only "exit_hook", but also other hooks, for example "deploy_cert".

This is a backwards incompatible change, which I'm not willing to do unless it's really required. Additionally, I don't think adding the ability to daisy chain hooks is a good idea. Note that it's trivial to extend the example hook with a call to `pdns_api.sh` instead, which would result in the same functionality.

**Comment by asmcc** [comment]
If you want, I can modify my version so, that it can be backwards compatible with this PDNS_DEPLOY_CERT_HOOK. If you want, I could introduce additionally a separate variable for my universal exit script. Otherwise it will be stay my own fork, which I will operate here separatelly.
An intergration of your script into dehydrated hook from example is to expensive. Calling of your script from dehydrated example hook is also to expensive to manage it. My proposal was to use your script in the middle between dehydrated and dehydrated example hook. The scheme in my proposal: dehydrated => pdns_api.sh => dehydrated_hook.sh and it is in my case cleanly solved with returns and consolidated exit instead of using these innumerable exits in the middle of subroutines.

**Comment by silkeh** [comment]
I'm not sure what is 'too expensive' about what I suggest. The cleanest option would probably be a new script containing something like this:

```bash
#!/usr/bin/env bash
set -e
pdns_api.sh "$@"
dehydrated_hook.sh "$@"
```

But a minor modification to the example hook would also work:

```bash
[...]
pdns_api.sh "$@" || exit 1

HANDLER="$1"; shift
[...]
```

As for the replacing of exits by returns, I'm not sure what that would actually improve in your case. `pdns_api.sh` has `set -e` ("Exit immediately if a command exits with a non-zero status"), so it can exit at any point.

**Comment by asmcc** [comment]
"set -e", "#!/usr/bin/env bash" and multiple exits are very bad techniques of shell programming. Before dehydrated and your script I did not saw it elsewhere (and I use shell programming at different devices and linuxes already since 20 years). By using of such techniques you generate unstructed and poor readable code, which is very error-prone. Last point is very important at OSS community, since you do not have time and manpower to test all possible cases of your code really. Using of returns instead of exits defines unbroken function calls and generates a more structed code. 
But our discussion here is obsolete: It is your script and if you do not accept my proposal, then I will not tilt at windmills here.

**Pull request closed without merging**
